spring:
  cloud:
    aws:
      region:
        static: ap-south-1
      credentials:
        access-key: AKIAVW6SP6Y52CBXAYIJ
        secret-key: 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
      stack:
        auto: false

application:
  bucket:
    name: atharsbucket