spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue: is_user_exists_for_restaurant
  exchange: user_exchange
  routing-key: user_restaurant_key
  user:
    queue: get_email_from_id
    exchange: user_exchange
    routing_Key : user_email_id_key
  menu:
    queue: menu_price_for_order
    exchange: menu_exchange
    routing_Key : price_order_key
  notification:
    restaurant:
      exchange: restaurant_notification_exchange
      routing_Key: restaurant_new_*
    user:
      exchange: user_notification_exchange
      routing_Key: user_booking_*