package cln.swiggy.partner.model.enums;

public enum EventType {
    ORDER_CREATED,
    INVENTORY_RESERVED,
    INVENTORY_RESERVATION_FAILED,
    PAYMENT_INITIATED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    ORDER_CONFIRMED,
    CANCEL_ORDER,
    CANCEL_INVENTORY_RESERVATION,
    NOTIFY_USER,
    NOTIFY_RESTAURANT,
    NOTIFY_PARTNER,
    SAGA_COMPLETED,
    SAGA_FAILED,
    SAGA_TIMEOUT,
    ORDER_FAILED, SAGA_RETRY
}
